const columns = [
  {name: "ID", uid: "id", sortable: true},
  {name: "NOMBRE", uid: "name", sortable: true},
  {name: "EDAD", uid: "age", sortable: true},
  {name: "MEMBRESIA", uid: "membership", sortable: true},
  {name: "GENERO", uid: "genre", sortable: true},
  {name: "EMAIL", uid: "email"},
  {name: "ESTADO", uid: "status", sortable: true},
  {name: "ACCIONES", uid: "actions"},
];

const statusOptions = [
  {name: "Activo", uid: "activo"},
  {name: "En Pausa", uid: "pausado"},
  {name: "Dado de baja", uid: "inactivo"},
];

const clients = [
  {
    id: 1,
    name: "Tony Reichert",
    membership: "Basica",
    membershipTime: "Trimestral",
    status: "activo",
    age: "29",
    genre: "M",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    name: "Zoey Lang",
    membership: "Basica",
    membershipTime: "Semestral",
    status: "pausado",
    age: "25",
    genre: "F",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    name: "Jane Fisher",
    membership: "Basica",
    membershipTime: "Semestral",
    status: "inactivo",
    age: "22",
    genre: "F",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    name: "William Howard",
    membership: "VIP",
    membershipTime: "Mensual",
    status: "activo",
    age: "28",
    genre: "M",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    name: "Kristen Copper",
    membership: "Gold",
    membershipTime: "Mensual",
    status: "activo",
    age: "24",
    genre: "F",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 6,
    name: "Brian Kim",
    membership: "Basica",
    membershipTime: "Trimestral",
    age: "29",
    genre: "M",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "brian.kim@example.com",
    status: "activo",
  },
  {
    id: 7,
    name: "Michael Hunt",
    membership: "Basica",
    membershipTime: "Mensual",
    status: "activo",
    age: "27",
    genre: "M",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    email: "michael.hunt@example.com",
  },
  {
    id: 8,
    name: "Samantha Brooks",
    membership: "Gold",
    membershipTime: "Mensual",
    status: "activo",
    age: "31",
    genre: "F",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    email: "samantha.brooks@example.com",
  },
  {
    id: 9,
    name: "Frank Harrison",
    membership: "Basica",
    membershipTime: "Anual",
    status: "activo",
    age: "33",
    genre: "M",
    avatar: "https://i.pravatar.cc/150?img=4",
    email: "frank.harrison@example.com",
  },
  {
    id: 10,
    name: "Emma Adams",
    membership: "Basica",
    membershipTime: "Mensual",
    status: "activo",
    age: "35",
    genre: "F",
    avatar: "https://i.pravatar.cc/150?img=5",
    email: "emma.adams@example.com",
  },
  {
    id: 11,
    name: "Brandon Stevens",
    membership: "Basica",
    membershipTime: "Semestral",
    status: "activo",
    age: "22",
    genre: "M",
    avatar: "https://i.pravatar.cc/150?img=8",
    email: "brandon.stevens@example.com",
  },
  {
    id: 12,
    name: "Megan Richards",
    membership: "Gold",
    membershipTime: "Anual",
    status: "activo",
    age: "28",
    genre: "F",
    avatar: "https://i.pravatar.cc/150?img=10",
    email: "megan.richards@example.com",
  },
  {
    id: 13,
    name: "Oliver Scott",
    membership: "VIP",
    membershipTime: "Anual",
    status: "inactivo",
    age: "37",
    genre: "M",
    avatar: "https://i.pravatar.cc/150?img=12",
    email: "oliver.scott@example.com",
  },
  {
    id: 14,
    name: "Grace Allen",
    membership: "Gold",
    membershipTime: "Mensual",
    status: "inactivo",
    age: "30",
    genre: "F",
    avatar: "https://i.pravatar.cc/150?img=16",
    email: "grace.allen@example.com",
  },
  {
    id: 15,
    name: "Noah Carter",
    membership: "Gold",
    membershipTime: "Mensual",
    status: "inactivo",
    age: "31",
    genre: "M",
    avatar: "https://i.pravatar.cc/150?img=15",
    email: "noah.carter@example.com",
  },
  {
    id: 16,
    name: "Ava Perez",
    membership: "VIP",
    membershipTime: "Mensual",
    status: "inactivo",
    age: "29",
    genre: "F",
    avatar: "https://i.pravatar.cc/150?img=20",
    email: "ava.perez@example.com",
  },
  {
    id: 17,
    name: "Liam Johnson",
    membership: "VIP",
    membershipTime: "Trimestral",
    status: "inactivo",
    age: "28",
    genre: "M",
    avatar: "https://i.pravatar.cc/150?img=33",
    email: "liam.johnson@example.com",
  },
  {
    id: 18,
    name: "Sophia Taylor",
    membership: "VIP",
    membershipTime: "Trimestral",
    status: "inactivo",
    age: "27",
    genre: "F",
    avatar: "https://i.pravatar.cc/150?img=29",
    email: "sophia.taylor@example.com",
  },
  {
    id: 19,
    name: "Lucas Harris",
    membership: "Basica",
    membershipTime: "Mensual",
    status: "inactivo",
    age: "32",
    genre: "M",
    avatar: "https://i.pravatar.cc/150?img=50",
    email: "lucas.harris@example.com",
  },
  {
    id: 20,
    name: "Mia Robinson",
    membership: "Basica",
    membershipTime: "Mensual",
    status: "activo",
    age: "26",
    genre: "F",
    avatar: "https://i.pravatar.cc/150?img=45",
    email: "mia.robinson@example.com",
  },
];

export {columns, clients, statusOptions};
